### ISSUE TITLE
There's nothing wrong with your program, im just stupid

### ISSUE THREAD

**Issue by Aarigator** [davidkrantz/FacebookChatStatistics#3]
Hi, basically I'm creating a quiz for my friends and I'd love to get access to our group chats stats for some questions. Your program seems ideal for this, however, I'm not that knowledgeble when it comes to this kinda thing, so I'm a bit stuck. Im trying to figure out how to run it but I'm at a loss. If you wouldn't mind helping me, I'd greatly appreciate it. Thanks.

**Comment by davidkrantz** [comment]
Hello, what a fun idea for a quiz!

I'd be happy to help! Sorry for not seeing this earlier.

- What operating system are you using?
- Do you have a working Python 3.x installation on your computer? If yes, which Python version are you using? (I have only run the code with <=3.6)

Also, I just updated the code since I got an error when I tried running it earlier today. Everything should be working now. Maybe this fixes your problem?

**Comment by Chweps** [comment]
Hello, I would like to reopen this issue, because I have the exact same problem.
I would love to see your programm running but I have litteraly no skills with Github&Python

**Comment by davidkrantz** [comment]
Hello @Chweps! For me to be able to help you, please explain in more detail what the issue is.

- At what part of the installation guide do you get stuck?
- What operating system are you using?

For you to be able to run the code you will need a working Python 3 installation on your computer. To check if you have this or how to install Python on your computer, I suggest turning to Google and try to find some other resources on that.

**Comment by Chweps** [comment]
First, about requirements.txt, I understood these are small programms found on Github to make your program work ? If yes, does downloading the source code of these program work ? I have trouble downloading things on github
Second, once I have all requirements, what do I do ? The commands you listed have an syntax error on python's programm

**Comment by davidkrantz** [comment]
Reopen if you are still interested in using the package.
